name: user_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  cupertino_icons: ^1.0.6
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  dio: ^5.5.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shimmer: ^3.0.0
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg.png
    - assets/avatar.avif

fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf